package com.example.karenlee.app.songlists;

import com.example.karenlee.app.MusicService;
import com.example.karenlee.app.Song;
import com.example.karenlee.app.db.SongBPMDbHelper;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * An interface into what a song list should be able to handle.
 * Created by brycewilley on 2/14/16.
 */
public interface ISongListGenerator extends Serializable {

    /**
     * Sets the music service to contain the music list generated by this object.
     * @param srv A music service (song player)
     * @param mDbHelper access to the music database to access songs and their bpm
     * @param bpm the basis bpm. Different implementations will use this differently
     * @return A reference to the list of songs, also given to the music service
     */
    public ArrayList<Song> fillList(MusicService srv, SongBPMDbHelper mDbHelper, double bpm);
}
